### PR TITLE
feat: added password strength meter

### PR DESCRIPTION
**Pull request by AlvaroIsrael**
Hey man I saw an youtube video with your project and wanted to contribute to it somehow, so after reading the documentation i saw the project was missing a password strength meter. Then I have decided to help with that and implemented that feature.
passwordStrengthMeter

### CODE REVIEW

**Comment by AlvaroIsrael** [comment]
I can't add a reviwer and i don't know why. If any of the owners can review and aprove my PR that would be awesome!

**Review by Mikael-R — CHANGES_REQUESTED** [review]
We have an algorithm to [check password strength](https://github.com/password-generator/password-check-strength). It's a npm open source package.
For organization and decoupling purposes use it :)

**Review by mateushnsoares — CHANGES_REQUESTED** [review]
I agree with @Mikael-R

**Comment by AlvaroIsrael** [comment]
Nice, thanks for the reply, i will use the existing package and change the pull request. Please do not close it yet! Thank you!

**Comment by AlvaroIsrael** [comment]
@Mikael-R and @mateushnsoares this functionality has already been implemented in the main branch so i will close this. Thanks!

**Pull request closed without merging**
